variables:
- template: variables/common.yml
- template: variables/dev.yml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

# variables:
#   buildConfiguration: 'Release'
#   dotnetVersion: '10.0.x'
#   functionProject: 'ProductManagerFunction.csproj'
#   publishDirectory: '$(Build.ArtifactStagingDirectory)/publish'

stages:
- stage: Build
  displayName: Build Function App

  jobs:
  - job: Build
    displayName: Restore, Build and Publish

    steps:

    - checkout: self

    - task: UseDotNet@2
      displayName: Install .NET SDK
      inputs:
        packageType: sdk
        version: $(dotnetVersion)

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: $(functionProject)

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        arguments: '--configuration $(buildConfiguration)'
        projects: $(functionProject)

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: false
        arguments: '--configuration $(buildConfiguration) --output $(publishDirectory)'
        projects: $(functionProject)
        zipAfterPublish: true

    - task: PublishPipelineArtifact@1
      displayName: Publish Artifact
      inputs:
        targetPath: $(publishDirectory)
        artifact: functionapp
- stage: 'Deploy_Infra_$(environment)'
  displayName: 'Deploy Infrastructure - $(environment)'
  dependsOn: Build
  jobs:
  - deployment: DeployInfrastructure
    displayName: Deploy Bicep
    environment: $(environment)
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: Deploy Resource Group
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az deployment sub create --location $(location) --template-file infra/subscription/resourceGroup.bicep --parameters applicationName=productmanager-api environment=$(environment) location=$(location) tags='{"Environment":$(environment),"Application":"ProductManagerApi","Owner":"NarayanaReddy","ManagedBy":"Bicep"}'
          - task: AzureCLI@2
            displayName: Deploy Infrastructure
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az deployment group create --resource-group $(resourceGroup) --template-file infra/resourceGroup/main.bicep --parameters infra/resourceGroup/parameters/$(environment).bicepparam

- stage: 'Deploy_Function_$(environment)'
  displayName: 'Deploy Function App - $(environment)'
  dependsOn: 'Deploy_Infra_$(environment)'
  jobs:
  - deployment: DeployFunction
    displayName: Deploy Function
    environment: $(environment)
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: functionapp
          - task: AzureFunctionApp@2
            displayName: Deploy Azure Function
            inputs:
              azureSubscription: 'sc-productmanager-$(environment)'
              appType: functionAppLinux
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/functionapp/**/*.zip'